name: verbal
favicon: null
layout_spectrum: 0.23999
typography_spectrum: 0.01099
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.3532282104715705
purpose: []
